name: Update Game Data
env:
  GITHUB_REPOSITORY: ${{ github.repository }}
on:
  schedule:
    # 每20分钟触发一次
    - cron: "*/20 * * * *"
  # 允许手动触发
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 添加写入权限
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # 更新到 v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # 使用默认的 GITHUB_TOKEN

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests ghp-import

      - name: Fetch and deploy data
        run: python scripts/fetch_game_data.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
